
services:
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    ports:
      - "8080:8080"
    depends_on:
      - db
    
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testezaretec
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
